export const ERROR_CODES = {
  // Authentication errors
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",

  // Validation errors
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_FORMAT: "INVALID_FORMAT",

  // Resource errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",

  // Business logic errors
  UNAUTHORIZED_ACTION: "UNAUTHORIZED_ACTION",
  REGISTRATION_CLOSED: "REGISTRATION_CLOSED",
  EVENT_FULL: "EVENT_FULL",
  ALREADY_REGISTERED: "ALREADY_REGISTERED",

  // Server errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
} as const;

