export const ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_OLD_PASSWORD: "INVALID_OLD_PASSWORD",
  CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

